### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by arpruss** [cjdaniel/sharp-wizard-games#1]
This is off-topic, but I am wondering if you happen to have a copy of my Loader application for the Wizard? It allowed one to have more than 10 programs at a time. Feel free to email me at arpruss@gmail.com

Thanks for posting these games!

Alex Pruss

**Comment by arpruss** [comment]
I found a copy. Sorry to have bothered you.

**Comment by cjdaniel** [comment]
Hi Alex,

Funny to hear from you after all these years! Glad you found it -- pretty sure I wouldn't have anything, anyway. Take care :-)
